bismilah_devise/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  resources :pages
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bismilah_devise/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

    # terdiri dari beberapa akses yaitu :

  user ||= User.new
  if user.has_role? :admin
    can :manage, :all
  elsif user.has_role? :author
    can :create, Article # author can create status
    can :update, Article # author can update status
    # can :destroy, Status # #uncomment this line, author can destroy status 
    can :read, :all
  elsif user.has_role? :guest
    can :read, :all
  end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

bismilah_devise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bismilah_devise/app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	validates :status, presence: true
end

bismilah_devise/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	 ROLES = %i[admin author guest]

	def roles=(roles)
	  roles = [*roles].map { |r| r.to_sym }
	  self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
	end

	def roles
	  ROLES.reject do |r|
	    ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
	  end
	end

	def has_role?(role)
	  roles.include?(role)
	end
end

bismilah_devise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	rescue_from CanCan::AccessDenied do |exception|
	  
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Cannot Procced this action , you dont have an access' }
    end
	  
	end

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up)  { |u| u.permit(  :email,:password, :password_confirmation, roles: []) }
	end
end

bismilah_devise/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    # respond_to do |format|
    #   format.html
    #   format.json { render json: ArticlesDatatable.new(view_context) }
    #   format.csv { send_data @articles.to_csv }
    #   format.xls { send_data @articles.to_csv(col_sep: "\t") }
    # end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :status)
    end
end

bismilah_devise/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@articles = Article.all
  end
end

bismilah_devise/app/helpers/application_helper.rb
module ApplicationHelper
end

bismilah_devise/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= form.label :title, class: "label-control" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, class: "label-control" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= form.label :status %>
      <%= form.radio_button :status, "Active" , :checked => true  %>
      <%= form.label :article_status, 'Active' %>
      <%= form.radio_button :status, "Off"  %>
      <%= form.label :article_status, 'Off' %>
  </div>

  <div class="actions">
    <%= form.submit "Simpan" , class: "btn btn-primary" %>
  </div>
<% end %>

bismilah_devise/app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

bismilah_devise/app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

bismilah_devise/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

bismilah_devise/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mb-4">Articles</h1>

<table id="articles" class="display" data-source="<%= articles_url(format: "json") %>" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th>Action</th>
      <th>Action</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.status %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

bismilah_devise/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

bismilah_devise/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @article.status %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

bismilah_devise/app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

bismilah_devise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test Auth and Login (with cancancan and Devise)</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'main' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'main' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "TestBlog", pages_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ml-auto justify-content-end">
          <li> <%= link_to "Home", pages_path, class: "nav-item nav-link" %></li>
          <li> 
            <% if can? :index, Article %>
              <%= link_to 'Dashboard', articles_path, class: "nav-item nav-link" %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %>
              <%= link_to "Log Out",destroy_user_session_path, method: :delete , class: "nav-item nav-link" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

bismilah_devise/app/views/pages/index.html.erb
<h1>Rails Blog</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

<div class="row mt-5">	
    <% @articles.each do |article| %>
  		<div class="col-md-4 mb-4">
  			<div class="card h-100 w-100" style="width: 18rem;">
				
			  	<div class="card-body">
				    <h5 class="card-title"><%= article.title %></h5>
				    <p class="card-text"><%= article.content %></p>
				    <%= link_to 'Show', article, class: 'btn btn-primary' %>
				</div>
	  		</div>
	  	</div>
	<% end %>
</div>